/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Hospital;

import Login.Login;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Егор
 */
public class Hospital extends javax.swing.JFrame {

    private JFrame frame;
    Login iLogin;

    /**
     * Creates new form Hospital
     */
    public Hospital() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtPrescription = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jbtnExit = new javax.swing.JButton();
        jbtnUpdate = new javax.swing.JButton();
        jbtnDelete = new javax.swing.JButton();
        jbtnDoctor = new javax.swing.JButton();
        jbtnGPAppointment = new javax.swing.JButton();
        jbtnPatient = new javax.swing.JButton();
        jbtnRevers = new javax.swing.JButton();
        jbtnLogin = new javax.swing.JButton();
        jbtnPharmacyOffce = new javax.swing.JButton();
        jbtnPrint = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jcmbNameTablets = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jlbRef = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtxtDose = new javax.swing.JTextField();
        jtxtRef = new javax.swing.JTextField();
        jtxtNumberTablets = new javax.swing.JTextField();
        jtxtLot = new javax.swing.JTextField();
        jtxtDailyDose = new javax.swing.JTextField();
        jtxtExpDate = new javax.swing.JTextField();
        jtxtIssuedDate = new javax.swing.JTextField();
        jtxtPossibleSideEffects = new javax.swing.JTextField();
        jtxtFurtherInformation = new javax.swing.JTextField();
        jtxtAdress = new javax.swing.JTextField();
        jtxtStorageAdvice = new javax.swing.JTextField();
        jtxtDrivingUsingMachines = new javax.swing.JTextField();
        jtxtHowtoUseMedication = new javax.swing.JTextField();
        jtxtPatiientID = new javax.swing.JTextField();
        jtxtDoctorNHSNo = new javax.swing.JTextField();
        jtxtPatiientName = new javax.swing.JTextField();
        jtxtDateBist = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableTT = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1400, 800));
        setPreferredSize(new java.awt.Dimension(1400, 800));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 60)); // NOI18N
        jLabel2.setText("Регистратура");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 1350, 90));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtPrescription.setColumns(20);
        jtxtPrescription.setRows(5);
        jScrollPane1.setViewportView(jtxtPrescription);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 330, 480));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 100, 350, 490));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Рецепт пациента");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 1070, 80));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnExit.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnExit.setText("Выход");
        jbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnExitActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 20, 110, -1));

        jbtnUpdate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnUpdate.setText("Обновить");
        jbtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnUpdateActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 140, -1));

        jbtnDelete.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnDelete.setText("Удалить");
        jbtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDeleteActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 140, -1));

        jbtnDoctor.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnDoctor.setText("Врач");
        jbtnDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDoctorActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnDoctor, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 140, -1));

        jbtnGPAppointment.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnGPAppointment.setText("Поликлиника");
        jbtnGPAppointment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGPAppointmentActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnGPAppointment, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 150, -1));

        jbtnPatient.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnPatient.setText("Пациент");
        jbtnPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPatientActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 140, -1));

        jbtnRevers.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnRevers.setText("Сброс");
        jbtnRevers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnReversActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnRevers, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, 120, -1));

        jbtnLogin.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnLogin.setText("Авторизация");
        jbtnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 20, 150, -1));

        jbtnPharmacyOffce.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnPharmacyOffce.setText("Рецепт");
        jbtnPharmacyOffce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPharmacyOffceActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnPharmacyOffce, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 20, 120, -1));

        jbtnPrint.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jbtnPrint.setText("Печать");
        jbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPrintActionPerformed(evt);
            }
        });
        jPanel4.add(jbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 100, -1));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 102, -1, 80));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 1340, 70));

        jcmbNameTablets.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jcmbNameTablets.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Сделайте выбор", "Аспирин", "Парцетомол", "АЦЦ" }));
        jcmbNameTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbNameTabletsActionPerformed(evt);
            }
        });
        getContentPane().add(jcmbNameTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, -1, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Название таблеток");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        jlbRef.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jlbRef.setText("Рег. №");
        getContentPane().add(jlbRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Дозировка (мг)");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel7.setText("Количество таблеток");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel8.setText("Масса");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel9.setText("Дата выпуска");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel10.setText("Срок годности");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel11.setText("Суточная доза");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, -1, -1));

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel12.setText("Побочные эффекты");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, -1, -1));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setText("Дополнительная информация");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, 280, 40));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel14.setText("Адрес пациента");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 520, -1, -1));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel15.setText("Рекомендации по хранению");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setText("Рекомендации для водителей");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, -1));

        jLabel17.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel17.setText("Инструкция по приему");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, -1, -1));

        jLabel18.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel18.setText("Пациент ID");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 360, -1, -1));

        jLabel19.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel19.setText("Страховой полис №");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 400, -1, -1));

        jLabel20.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel20.setText("Имя пациента");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, -1, -1));

        jLabel21.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel21.setText("Дата рождения");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 480, -1, -1));

        jtxtDose.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(jtxtDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 280, 180, -1));

        jtxtRef.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(jtxtRef, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 180, -1));

        jtxtNumberTablets.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtxtNumberTablets.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNumberTabletsActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtNumberTablets, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 180, -1));

        jtxtLot.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(jtxtLot, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 360, 180, -1));

        jtxtDailyDose.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtxtDailyDose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDailyDoseActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtDailyDose, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 480, 180, -1));

        jtxtExpDate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(jtxtExpDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 180, -1));

        jtxtIssuedDate.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtxtIssuedDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIssuedDateActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtIssuedDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 180, -1));

        jtxtPossibleSideEffects.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(jtxtPossibleSideEffects, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 520, 180, -1));

        jtxtFurtherInformation.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtxtFurtherInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtFurtherInformationActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtFurtherInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 200, 180, -1));

        jtxtAdress.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(jtxtAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 520, 180, -1));

        jtxtStorageAdvice.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtxtStorageAdvice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtStorageAdviceActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtStorageAdvice, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 180, -1));

        jtxtDrivingUsingMachines.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(jtxtDrivingUsingMachines, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, 180, -1));

        jtxtHowtoUseMedication.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtxtHowtoUseMedication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtHowtoUseMedicationActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtHowtoUseMedication, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 320, 180, -1));

        jtxtPatiientID.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(jtxtPatiientID, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 360, 180, -1));

        jtxtDoctorNHSNo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jtxtDoctorNHSNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtDoctorNHSNoActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtDoctorNHSNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 400, 180, -1));

        jtxtPatiientName.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(jtxtPatiientName, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 180, -1));

        jtxtDateBist.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getContentPane().add(jtxtDateBist, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 480, 180, -1));

        jTableTT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Название таблеток", "Справка №", "Дозировка (мг)", "Кол-во таблеток", "Масса", "Дата выпуска", "Срок годности", "Суточная доза", "Побочные эффекты", "Доп. информация", "Рек. по хранению", "Рек. для водителей", "Инструкция по приему", "Пациент ID", "Страховой полис №", "Имя пациента", "Дата рождения", "Адрес пациента"
            }
        ));
        jScrollPane4.setViewportView(jTableTT);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, 1340, 90));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNumberTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNumberTabletsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNumberTabletsActionPerformed

    private void jtxtDailyDoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDailyDoseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDailyDoseActionPerformed

    private void jtxtIssuedDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIssuedDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIssuedDateActionPerformed

    private void jtxtFurtherInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtFurtherInformationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtFurtherInformationActionPerformed

    private void jtxtStorageAdviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtStorageAdviceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtStorageAdviceActionPerformed

    private void jtxtHowtoUseMedicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtHowtoUseMedicationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtHowtoUseMedicationActionPerformed

    private void jtxtDoctorNHSNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtDoctorNHSNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtDoctorNHSNoActionPerformed

    private void jbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPrintActionPerformed
        try {
            jtxtPrescription.print();
        } catch (PrinterException ex) {
            Logger.getLogger(Hospital.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jbtnPrintActionPerformed

    private void jbtnDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDoctorActionPerformed
        this.setVisible(false);
        iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jbtnDoctorActionPerformed

    private void jbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnExitActionPerformed
        frame = new JFrame();
        if (JOptionPane.showConfirmDialog(frame, "Хотите выйти?", "Регистратура",
                JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_jbtnExitActionPerformed

    private void jcmbNameTabletsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbNameTabletsActionPerformed
        if (jcmbNameTablets.getSelectedItem().equals("Аспирин")) {
            jtxtRef.setText("Асп343538");
            jtxtDose.setText("2");
            jtxtNumberTablets.setText("32");
            jtxtLot.setText("414324242");
            jtxtIssuedDate.setText("06/02/2023");
            jtxtExpDate.setText("04/02/2024");
            jtxtDailyDose.setText("4");

            jtxtPossibleSideEffects.setText("Кровотечение");
            jtxtFurtherInformation.setText("При комнатной температуре");
            jtxtStorageAdvice.setText("Менее 20%");
            jtxtDrivingUsingMachines.setText("Не рекомендируется");
            jtxtHowtoUseMedication.setText("Алкоголь запрещен");
            jtxtPatiientID.setText("P1214423");
            jtxtDoctorNHSNo.setText("3124-244-234");
        } else if (jcmbNameTablets.getSelectedItem().equals("Парцетомол")) {
            jtxtRef.setText("Пар343538");
            jtxtDose.setText("1");
            jtxtNumberTablets.setText("23");
            jtxtLot.setText("6788875");
            jtxtIssuedDate.setText("06/03/2023");
            jtxtExpDate.setText("04/03/2024");
            jtxtDailyDose.setText("3");

            jtxtPossibleSideEffects.setText("Головокружение");
            jtxtFurtherInformation.setText("При температуре на выше +5");
            jtxtStorageAdvice.setText("Менее 30%");
            jtxtDrivingUsingMachines.setText("Не рекомендируется");
            jtxtHowtoUseMedication.setText("Алкоголь запрещен");
            jtxtPatiientID.setText("Y1214423");
            jtxtDoctorNHSNo.setText("3124-244-567");
        } else if (jcmbNameTablets.getSelectedItem().equals("АЦЦ")) {
            jtxtRef.setText("АЦЦ3400038");
            jtxtDose.setText("4");
            jtxtNumberTablets.setText("45");
            jtxtLot.setText("5765674");
            jtxtIssuedDate.setText("05/03/2023");
            jtxtExpDate.setText("05/04/2024");
            jtxtDailyDose.setText("8");

            jtxtPossibleSideEffects.setText("Отсутствуют");
            jtxtFurtherInformation.setText("Отсутствуют");
            jtxtStorageAdvice.setText("Менее 20%");
            jtxtDrivingUsingMachines.setText("Не рекомендируется");
            jtxtHowtoUseMedication.setText("Алкоголь не рекомендуются");
            jtxtPatiientID.setText("Ф1214423");
            jtxtDoctorNHSNo.setText("3124-345-567");
        } else if (jcmbNameTablets.getSelectedItem().equals("Сделайте выбор")) {
            jtxtRef.setText("");
            jtxtDose.setText("");
            jtxtNumberTablets.setText("");
            jtxtLot.setText("");
            jtxtIssuedDate.setText("");
            jtxtExpDate.setText("");
            jtxtDailyDose.setText("");

            jtxtPossibleSideEffects.setText("");
            jtxtFurtherInformation.setText("");
            jtxtStorageAdvice.setText("");
            jtxtDrivingUsingMachines.setText("");
            jtxtHowtoUseMedication.setText("");
            jtxtPatiientID.setText("");
            jtxtDoctorNHSNo.setText("");
        }
    }//GEN-LAST:event_jcmbNameTabletsActionPerformed

    private void jbtnPharmacyOffceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPharmacyOffceActionPerformed
        String Qty1 = (jtxtRef.getText());
        String Qty2 = (jtxtDose.getText());
        String Qty3 = (jtxtNumberTablets.getText());
        String Qty4 = (jtxtLot.getText());
        String Qty5 = (jtxtDailyDose.getText());
        String Qty6 = (jtxtPossibleSideEffects.getText());
        String Qty7 = (jtxtFurtherInformation.getText());
        String Qty8 = (jtxtHowtoUseMedication.getText());
        String Qty9 = (jtxtPatiientID.getText());
        String Qty10 = (jtxtPatiientName.getText());
        String Qty11 = (jtxtDateBist.getText());
        String Qty12 = (jtxtAdress.getText());
        String Qty13 = "";

        if (jcmbNameTablets.getSelectedItem().equals("Аспирин")) {
            Qty13 = "Аспирин";
        } else if (jcmbNameTablets.getSelectedItem().equals("Парцетомол")) {
            Qty13 = "Парцетомол";
        }
        if (jcmbNameTablets.getSelectedItem().equals("АЦЦ")) {
            Qty13 = "АЦЦ";
        }

        jtxtPrescription.setText("");
        jtxtPrescription.append("\t\n\tРегистратура"
                + "\t\n\tРецепт пациента\n"
                + "\nИмя пациента:\t" + Qty10
                + "\nДата рождения:\t" + Qty11
                + "\nАдресс пациента:\t" + Qty12
                + "\nРецепт:\t\t" + Qty13
                + "\nРег. №:\t\t" + Qty1
                + "\nДозировка (мг):\t" + Qty2
                + "\nКоличество таблеток:\t" + Qty3
                + "\nВес:\t\t" + Qty4
                + "\nСуточная доза:\t" + Qty5
                + "\nПобочные эффекты:\t" + Qty6
                + "\nДоп. информация:\t" + Qty7
                + "\nИнструкция по прм.:\t" + Qty8
                + "\nПациент ID:\t\t" + Qty9
        );
    }//GEN-LAST:event_jbtnPharmacyOffceActionPerformed

    private void jbtnReversActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnReversActionPerformed
        jtxtRef.setText("");
        jtxtDose.setText("");
        jtxtNumberTablets.setText("");
        jtxtLot.setText("");
        jtxtIssuedDate.setText("");
        jtxtExpDate.setText("");
        jtxtDailyDose.setText("");

        jtxtPossibleSideEffects.setText("");
        jtxtFurtherInformation.setText("");
        jtxtStorageAdvice.setText("");
        jtxtDrivingUsingMachines.setText("");
        jtxtHowtoUseMedication.setText("");
        jtxtPatiientID.setText("");
        jtxtDoctorNHSNo.setText("");
        jcmbNameTablets.getModel().setSelectedItem("Сделайте выбор");

        jtxtPatiientName.setText("");
        jtxtDateBist.setText("");
        jtxtAdress.setText("");
    }//GEN-LAST:event_jbtnReversActionPerformed

    private void jbtnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginActionPerformed
        this.setVisible(false);
        iLogin = new Login();
        iLogin.setVisible(true);


    }//GEN-LAST:event_jbtnLoginActionPerformed

    private void jbtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnUpdateActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTableTT.getModel();
        model.addRow(new Object[]{jcmbNameTablets.getSelectedItem().toString(),
            jtxtRef.getText(),
            jtxtDose.getText(),
            jtxtNumberTablets.getText(),
            jtxtLot.getText(),
            jtxtIssuedDate.getText(),
            jtxtExpDate.getText(),
            jtxtDailyDose.getText(),
            jtxtPossibleSideEffects.getText(),
            jtxtFurtherInformation.getText(),
            jtxtStorageAdvice.getText(),
            jtxtDateBist.getText(),
            jtxtDrivingUsingMachines.getText(),
            jtxtHowtoUseMedication.getText(),
            jtxtPatiientID.getText(),
            jtxtDoctorNHSNo.getText(),
            jtxtPatiientName.getText(),
            jtxtDateBist.getText(),
            jtxtAdress.getText(),});
    }//GEN-LAST:event_jbtnUpdateActionPerformed

    private void jbtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDeleteActionPerformed
        DefaultTableModel model = (DefaultTableModel) jTableTT.getModel();
        if (jTableTT.getSelectedRow() == -1) {
            if (jTableTT.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Нет данных для удаления!",
                        "Регистратура", JOptionPane.OK_OPTION);
            } else {
                JOptionPane.showMessageDialog(null, "Выберите строку для удаления!",
                        "Регистратура", JOptionPane.OK_OPTION);
            }
        } else {
            model.removeRow(jTableTT.getSelectedRow());
        }
    }//GEN-LAST:event_jbtnDeleteActionPerformed

    private void jbtnGPAppointmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGPAppointmentActionPerformed
        this.setVisible(false);
        iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jbtnGPAppointmentActionPerformed

    private void jbtnPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPatientActionPerformed
        this.setVisible(false);
        iLogin = new Login();
        iLogin.setVisible(true);
    }//GEN-LAST:event_jbtnPatientActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hospital.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hospital().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTableTT;
    private javax.swing.JButton jbtnDelete;
    private javax.swing.JButton jbtnDoctor;
    private javax.swing.JButton jbtnExit;
    private javax.swing.JButton jbtnGPAppointment;
    private javax.swing.JButton jbtnLogin;
    private javax.swing.JButton jbtnPatient;
    private javax.swing.JButton jbtnPharmacyOffce;
    private javax.swing.JButton jbtnPrint;
    private javax.swing.JButton jbtnRevers;
    private javax.swing.JButton jbtnUpdate;
    private javax.swing.JComboBox<String> jcmbNameTablets;
    private javax.swing.JLabel jlbRef;
    private javax.swing.JTextField jtxtAdress;
    private javax.swing.JTextField jtxtDailyDose;
    private javax.swing.JTextField jtxtDateBist;
    private javax.swing.JTextField jtxtDoctorNHSNo;
    private javax.swing.JTextField jtxtDose;
    private javax.swing.JTextField jtxtDrivingUsingMachines;
    private javax.swing.JTextField jtxtExpDate;
    private javax.swing.JTextField jtxtFurtherInformation;
    private javax.swing.JTextField jtxtHowtoUseMedication;
    private javax.swing.JTextField jtxtIssuedDate;
    private javax.swing.JTextField jtxtLot;
    private javax.swing.JTextField jtxtNumberTablets;
    private javax.swing.JTextField jtxtPatiientID;
    private javax.swing.JTextField jtxtPatiientName;
    private javax.swing.JTextField jtxtPossibleSideEffects;
    private javax.swing.JTextArea jtxtPrescription;
    private javax.swing.JTextField jtxtRef;
    private javax.swing.JTextField jtxtStorageAdvice;
    // End of variables declaration//GEN-END:variables
}
